AISET/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AISET.Models;

using AISET.Repository.BL;
namespace AISET.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            RegisterModels models = new RegisterModels();

            models._StudentList = clsLoginBL.GetAllStudentList();








            return View(models);
        }



        public ActionResult GenerateAdmitCard()
        {
            return View();
        }
        [HttpGet]
        public ActionResult UpdateEditDate()
        {
            EditUpdateDateModels models = new EditUpdateDateModels();
            models.LastEditDate = clsLoginBL.GetLastDateForEdit();
            return View(models);
        }

        [HttpPost]
        public ActionResult UpdateEditDate(EditUpdateDateModels models)
        {
            if (ModelState.IsValid)
            {
                clsLoginBL.UpdateLastDateForEdit(models.LastEditDate.ToString());
                ViewBag.Message = "Record Updated Sucessfully";
            }
            return View(models);
        }

    }
}

AISET/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AISET.Models;
using AISET.Repository.BL;
namespace AISET.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        [HttpGet]
        public ActionResult Index()
        {
            StudentModels models = new StudentModels();
            models = clsLoginBL.BindStudentDetailsByID(Convert.ToInt32(Session[SessionVariable.UserID].ToString()));


            return View(models);
        }
        [HttpPost]
        public ActionResult Index(StudentModels models)
        {

            if (ModelState.IsValid)
            {

                ResponseModels rsp = clsLoginBL.UpdateStudentDetails(models);
                if (rsp.Response == MethodResponse.Success)
                {
                    ViewBag.Message = "The Record has been Updated Successfully.";
                }
                else
                {
                    ViewBag.Message = "Something went wrong please try again.";
                }
            }


            return View(models);
        }


        public ActionResult ExamResults()
        {
            return View();
        }
        public ActionResult AdmitCard()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ChangePassword()
        {



            return View();
        }
        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordViewModel models)
        {

            if (ModelState.IsValid)

            {
                if (models.OldPassword != Session[SessionVariable.Password].ToString())
                {
                    ModelState.AddModelError("", "The current Password does not match.");
                    return View(models);
                }
                ViewBag.Message = "The Password changed successfully.";
                models.UserID = Convert.ToInt32(Session[SessionVariable.UserID].ToString());
                clsLoginBL.ChangePassword(models);
            }
            else

            {
                ModelState.AddModelError("", "Something went wrong please try again");
            }

            return View(models);
        }
    }
}

AISET/Views/Student/AdmitCard.cshtml
@{
    ViewBag.Title = "AdmitCard";
    Layout = "~/Views/Shared/_LayoutStudent.cshtml";
}

<h1>Comming Soon</h1>

AISET/Views/Student/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_LayoutStudent.cshtml";
}


@model AISET.Models.ChangePasswordViewModel

<script>
    //   $(".profile-menu").addClass('toggled'); //overflow: hidden; display: block;
    //  $(".main-menu").css("display", "block");

</script>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Change Password</h1>
    </div>
</div>
<div style="padding-left: 10px;">


    @using (Html.BeginForm("ChangePassword", "Student", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <h1>@ViewBag.Message </h1>
        @Html.ValidationSummary()

        <div>
            <div class="form-group">
            </div>
            <div class="form-group">
                <div class="input-group field">
                    <span class="input-group-addon">
                        <i class="fa fa-wrench"></i>
                    </span>
                    @Html.PasswordFor(m => m.OldPassword, new { @class = "form-control", @placeholder = "Current Password*" })

                </div>
            </div>
            <div class="form-group">
                <div class="input-group field">
                    <span class="input-group-addon">
                        <i class="fa fa-key"></i>
                    </span>
                    @Html.PasswordFor(m => m.NewPassword, new { @class = "form-control", @placeholder = "New Password*" })
                </div>
            </div>
            <div class="form-group">
                <div class="input-group field">
                    <span class="input-group-addon">
                        <i class="fa fa-key"></i>
                    </span>
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Confirm Password*" })
                </div>
            </div>
        </div>
        <div class="form-group clear">
            &nbsp;&nbsp;&nbsp;&nbsp;
            <button type="submit" value="Update" class="btn btn-success waves-effect waves-effect">Update</button>&nbsp;&nbsp;
            <a href="@Url.Action("Index", "Admin")" class="btn btn-warning waves-effect waves-effect">Cancel</a>
        </div>
    }
</div>
<script>
    $(document).ready(function () {




    });
    function kk() {

        swal({
            title: "",
            text: "Has Agregado un Usuario Nuevo!sdfsf sf sfs fs f s f s fs f s f s f sdf sdf s f sfd s fs f s fdsdf s df s f sdf s dfs df sdf s d",
            closeOnConfirm: false
        },
            function () {
                swal.close();
                $("#OldPassword").focus();

            });
    }
</script>

AISET/Views/Student/ExamResults.cshtml
@{
    ViewBag.Title = "ExamResults";
    Layout = "~/Views/Shared/_LayoutStudent.cshtml";
}

<h2>Comming Soon</h2>

AISET/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutStudent.cshtml";

}

@model AISET.Models.StudentModels





<div class="panel panel-primary">

    <div class="panel-body">


        @using (Html.BeginForm("Index", "Student", FormMethod.Post))
        {

            <h3>@ViewBag.Message</h3>
            @Html.ValidationSummary()
            @Html.HiddenFor(m => m.StudentID)
            <div class="form-group">
                <label for="email">First Name:</label>
                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })

            </div>
            <div class="form-group">
                <label for="pwd">Last Name:</label>
                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="pwd">DOB:</label>
                @Html.TextBoxFor(m => m.DOB, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="pwd">Email:</label>
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @readonly = "readonly" })
            </div>

            <div class="form-group">
                <label for="pwd">Mobile No:</label>
                @Html.TextBoxFor(m => m.MobileNo, new { @class = "form-control" })
            </div>
            <button type="submit" class="btn-block btn btn-primary">Update</button>
        }

    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}